export const institutions = [
  "Arizona State University",
  "Boston College",
  "Boston University",
  "Brown University",
  "California Institute of Technology",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Drake University",
  "Duke University",
  "Emory University",
  "Florida State University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Grand View University",
  "Harvard University",
  "Indiana University",
  "Iowa State University",
  "Johns Hopkins University",
  "Massachusetts Institute of Technology",
  "Michigan State University",
  "New York University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Penn State University",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Rutgers University",
  "Stanford University",
  "Syracuse University",
  "Texas A&M University",
  "Tufts University",
  "Tulane University",
  "University of Alabama",
  "University of Arizona",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of Southern California",
  "University of Texas at Austin",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Yale University",
  "Other"
] as const;

export type Institution = typeof institutions[number];
